### ISSUE TITLE
Unknown authentication strategy "kakao" Error: Unknown authentication strategy "kakao"

### ISSUE THREAD

**Issue by Singularity2050** [ZeroCho/nodejs-book#104]
380페이지 쳅터 9.3에서 이 에러가 왜 계속 뜨는지 모르겠어요 ㅠㅠ 도와주세요 ㅠㅠ

**Comment by ZeroCho** [comment]
passport/index.js에서 local() 밑에 kakao() 있나요?

**Comment by Singularity2050** [comment]
![스크린샷 2020-08-14 오후 4 19 38](https://user-images.githubusercontent.com/67400401/90224059-120cdb00-de4a-11ea-921a-0fbeb9ab7a28.png)

**Comment by Singularity2050** [comment]
네넵 있습니다! 빠른답변 감동입니다...

**Comment by Singularity2050** [comment]
![스크린샷 2020-08-14 오후 4 21 43](https://user-images.githubusercontent.com/67400401/90224186-3f598900-de4a-11ea-8e10-6fc0336c9041.png)
kakaoStrategy.js 파일입니다.

**Comment by Singularity2050** [comment]
callbackURL 이 /auth/kakao/callback 으로 했는데 안되서  URL로 썼어요 ㅠㅠ

**Comment by Singularity2050** [comment]
![스크린샷 2020-08-14 오후 4 23 57](https://user-images.githubusercontent.com/67400401/90224400-8fd0e680-de4a-11ea-980e-82d09cbfb75f.png)
auth.js 파일입니다!

**Comment by Singularity2050** [comment]
![스크린샷 2020-08-14 오후 4 26 16](https://user-images.githubusercontent.com/67400401/90224613-e2120780-de4a-11ea-8080-e36224b232e8.png)
파일트리 모습입니다!

**Comment by Singularity2050** [comment]
![스크린샷 2020-08-14 오후 4 51 55](https://user-images.githubusercontent.com/67400401/90226806-88134100-de4e-11ea-9e74-dea9de95ce11.png)
혹시 웹페이지에서는 카톡로그인이 안된다는데 이것때문인가요?

**Comment by ZeroCho** [comment]
일반 이메일/비밀번호 로그인은 잘 되나요? 카카오 로그인은 JavaScript SDK가 아니라 REST API라서 웹에서도 가능합니다.

**Comment by Singularity2050** [comment]
![스크린샷 2020-08-16 오후 2 45 05](https://user-images.githubusercontent.com/67400401/90327510-14e50880-dfcf-11ea-96b1-5b69530d78da.png)
passport 를 못가져 오는것 같습니다 ㅠㅠ

**Comment by Singularity2050** [comment]
![스크린샷 2020-08-16 오후 2 48 19](https://user-images.githubusercontent.com/67400401/90327547-891fac00-dfcf-11ea-8e7d-f3c27331aca7.png)
auth.js 에서 
  passport.authenticate('local', (authError, user, info) => { 
여기서 local를 인식못하는것 같습니다.

**Comment by ZeroCho** [comment]
app.js에서 passport불러와서 실행하셨나요? 제 app.js랑 비교해보세요.

**Comment by Singularity2050** [comment]
감사합니다! 해결완료 됬습니다. passportCofig();를 빠뜨렸었네요 ㅠㅠ
