### ISSUE TITLE
오타 :: 개정2판 초판(20년7월25일) 411쪽 - timestamps, paranoid가 false로 표시되어있습니다.

### ISSUE THREAD

**Issue by wonjinYi** [ZeroCho/nodejs-book#127]
안녕하세요, 책 항상 잘 보고 있습니다. 

2019년에 마지막으로 수정된 해당 repo의 코드와, 책에 적혀있는 코드 내용이 달라 이슈 남깁니다.

1. [깃허브 예제코드](https://github.com/ZeroCho/nodejs-book/blob/master/ch9/9.2/nodebird/models/user.js) (9.2 - models/user.js)
30행 timestamps : **true**
34행 paranoid : **true**

2. 개정2판 초판(20년7월25일) 411쪽 
밑에서 12번째줄 timestamps : **false**
밑에서 8번째줄 paranoid : **false**

뒤에 나오는 설명에서는 " ... timestamps와 paranoid가 true 주어졌으므로 ... " 라고 합니다.
깃헙에 올라온 코드내용이 책에 반영안되었나봐요

시간되실 때 확인 부탁드립니다.

**Comment by ZeroCho** [comment]
#102 
여기서 추적 중이어서 2쇄에서 수정되었습니다. 감사합니다.
