### ISSUE TITLE
Node.js교과서 8장의 mongodb

### ISSUE THREAD

**Issue by heecheol153** [ZeroCho/nodejs-book#129]
ebook으로 공부중인데요,,,
8장과 12장에서 몽고디비관련에서 에러로 잘진행되지가 않아요...
책의 예제대로 입력해서 했는데 에러발생...
예제,등 순서/설치 설명에 틀린점이 없는지요...
3일째 고생중입니다...ㅠㅠ 

  console.error('몽고디비 연결이 끊겼습니다. 연결을 재시도합니다.');
만 자주뜹니다...

**Comment by ZeroCho** [comment]
그 위에 console.error(error)도 입력해보세요.
혹시 서버 실행 전에 몽고디비 실행하셨나요? mongod.exe나 cmd에서 명령어 치셔서요.
그리고 개정판이신가요(Node14) 초판이신가요?

**Comment by heecheol153** [comment]
회답에 감사합니다.
말씀대로 해봤더니.
(1)  console.error(error)를 넣은결과   " '몽고디비 연결이 끊겼습니다. 연결을 재시도합니다.'  "표시는 안 나오고, 맨 밑에 아래와같이 에러가 나옵니다...
.....
at /Users/heecheol/learn-express/gif-chat/node_modules/mongoose/lib/index.js:342:10
[nodemon] app crashed - waiting for file changes before starting...

(2)사용환경은 macOS 10.15.7입니다.
(3)책은 "Node.js교과서 개정2판" 이고 ePub전자책 2쇄발행 2020년9월20일 입니다.
(4)아래와 같이 mongod 프로세스가 실행상태....
$ ps -ef | grep mongod | grep -v grep
 501 10383     1   0  1:07PM ??     0:17.15 /usr/local/opt/mongodb-community/bin/mongod --config /usr/local/etc/mongod.conf

JavaScript, Node.js는  처음 해보는거라.. 초~초보자라서 ... 
오늘도 아침부터 진행중..안풀리네요... 
이책의 샘플 "채팅"과 "실시간 경매 시스템"을 만들어보기위해 9월 부터진행중인데요..마침 채팅이 몽고 디비라...
(본업:Database Administrator)

**Comment by ZeroCho** [comment]
(1)번 부분에서 에러 가장 마지막만 보여주셨습니다. 에러 제일 윗줄이 제일 중요합니다.

**Comment by heecheol153** [comment]
![ch8_mongoose_error01](https://user-images.githubusercontent.com/58098392/95959585-9de8b680-0e3d-11eb-9568-82fe1ae2c707.png)

회답 감사합니다.
에러부분을 첨부합니다...^^;

**Comment by ZeroCho** [comment]
error is not defined라고 되어있는데 schemas/index.js에서
```
mongoose.connection.on('disconnected', (error) => {
```
로 바꾸세요.
그러면 제대로 된 에러가 표시될 것입니다.

**Comment by heecheol153** [comment]
회답 감사합니다.
그후 8장을 선생님의 github에 올린소스를 전부 다시 복사 해본결과 다시 이전상태의 에러가 발생했고,
위 말씀대로 schemas/index를 수정한결과가 아래와 같이 나옵니다. 

![ch8_mongoose_error02](https://user-images.githubusercontent.com/58098392/95976248-2cffc980-0e52-11eb-8e52-6b9e3c558f6a.png)
![ch8_mongoose_error03](https://user-images.githubusercontent.com/58098392/95976269-34bf6e00-0e52-11eb-9627-ef1748377598.png)

**Comment by heecheol153** [comment]
안녕하세요.
오늘 이제서야 잘 됩니다. 오늘 선생님의 소스를 다운로드해서 처음부터 다시 해보니 에러가 사라지고 기대화면이 띄워졌습니다.
지금까진 책보면서 코딩을 옮겨가면서 했는데...어딘선가 코딩또는 환경미스가 있던것 같습니다.
덕분에 에러 표시방법 하나 알게되어 감사합니다..
계속해서 진행중입니다...
감사합니다..
