### ISSUE TITLE
10.4 nodebird-api 부분 관련 질문드립니다.(초판 5쇄)

### ISSUE THREAD

**Issue by rurusyu** [ZeroCho/nodejs-book#130]
올드 브랜치에서 10.4 챕터 nodebird-api 부분에서 localhost:8002/v1/token 으로 하는데도 계속 없다고 뜨길래..

제로초님 old 브랜치에 10.4 챕터 그대로 들고와서 해보는데도 계속 404가 뜨네요..

nodebird-call 부분도 localhost:8003/test 해도 401만 계속 뜨네요...

**Comment by ZeroCho** [comment]
POST /token이 404인 이유는 라우터를 연결하지 않으신 것 같습니다.
app.js에서 v1 router 연결하셨나요?

**Comment by rurusyu** [comment]
네네 연결했고, 401로 유효하지 않은 토큰입니다가 계속 뜨네용ㅠ

**Comment by ZeroCho** [comment]
localhost:8002에서 도메인 등록은 하셨나요?

**Comment by rurusyu** [comment]
네네 hocalhost:8003 으로 도메인 등록했구 발급받은 key는 call서버의 .env에 CLIENT_SECRET으로 넣었습니당~

**Comment by ZeroCho** [comment]
401뜰 때 response가 무엇인가요? '등록되지 않은 도메인입니다. 먼저 도메인을 등록하세요' 이게 맞나요?

**Comment by rurusyu** [comment]
localhost:8003/test 는 잘나오네용.

localhost:8002/v1/token 은 여전히 404구용..


localhost:8002/v1/test 은 여전히 401 이구용..(유효하지 않은 토큰 입니다) 라고 뜨네용..

app.js에 

const v1 = require('./routes/v1');

app.use('/v1', v1); 이렇게 연결도 잘했구..

디비에는 잘 들어가있구용..

![image](https://user-images.githubusercontent.com/24752389/96809120-36da8b80-1455-11eb-983e-7640abcf5867.png)

**Comment by rurusyu** [comment]
아래는 api > v1.js
`const express = require('express');
const jwt = require('jsonwebtoken');

const { verifyToken } = require('./middlewares');
const { Domain, User, Post, Hashtag } = require('../models');

const router = express.Router();

router.post('/token', async (req, res) => {
  const { clientSecret } = req.body;
  try {
    const domain = await Domain.findOne({
      where: { clientSecret },
      include: {
        model: User,
        attribute: ['nick', 'id'],
      },
    });
    if (!domain) {
      return res.status(401).json({
        code: 401,
        message: '등록되지 않은 도메인입니다. 먼저 도메인을 등록하세요',
      });
    }
    const token = jwt.sign({
      id: domain.user.id,
      nick: domain.user.nick,
    }, process.env.JWT_SECRET, {
      expiresIn: '1m', // 1분
      issuer: 'nodebird',
    });
    return res.json({
      code: 200,
      message: '토큰이 발급되었습니다',
      token,
    });
  } catch (error) {
    console.error(error);
    return res.status(500).json({
      code: 500,
      message: '서버 에러',
    });
  }
});

router.get('/test', verifyToken, (req, res) => {
  res.json(req.decoded);
});

module.exports = router;
`

아래는 api의 app.js 입니다.

`const express = require('express');
const path = require('path');
const cookieParser = require('cookie-parser');
const passport = require('passport');
const morgan = require('morgan');
const session = require('express-session');
const flash = require('connect-flash');
require('dotenv').config();

const { sequelize } = require('./models');
const passportConfig = require('./passport');
const authRouter = require('./routes/auth');
const indexRouter = require('./routes');
const v1 = require('./routes/v1');

const app = express();
sequelize.sync();
passportConfig(passport);

app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'pug');
app.set('port', process.env.PORT || 8002);

app.use(morgan('dev'));
app.use(express.static(path.join(__dirname, 'public')));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser(process.env.COOKIE_SECRET));
app.use(session({
  resave: false,
  saveUninitialized: false,
  secret: process.env.COOKIE_SECRET,
  cookie: {
    httpOnly: true,
    secure: false,
  },
}));
app.use(flash());
app.use(passport.initialize());
app.use(passport.session());

app.use('/v1', v1);
app.use('/auth', authRouter);
app.use('/', indexRouter);

app.use((req, res, next) => {
  const err = new Error('Not Found');
  err.status = 404;
  next(err);
});

app.use((err, req, res, next) => {
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};
  res.status(err.status || 500);
  res.render('error');
});

app.listen(app.get('port'), () => {
  console.log(app.get('port'), '번 포트에서 대기중');
});
`

**Comment by ZeroCho** [comment]
localhost:8002는 왜 접근하시는 건가요? 걔네 둘은 브라우저로 접근하는 API가 아닙니다.

**Comment by rurusyu** [comment]
아 이제 이해했네요 ㅎㅎ 감사합니다!!
