### ISSUE TITLE
hasMamy, belongsToMany

### ISSUE THREAD

**Issue by JeongHoon-Park** [ZeroCho/nodejs-book#18]
안녕하세요. zerocho님, 어디다 질문해야할지 잘 모르겠어서 여기다가 올리긴 하는데 실례일런지 모르겠네요.

Node.js 교과서 362p  Chapter 9  models/index.js 예제 코드를 옮겨서 실행해 봤는데, 계속해서 에러가 뜹니다. 

C:\report-card\Node-SNS\models\index.js:15
db.User.hasMany(db.Post);
Cannot read property 'hasMany' of undefined

hasMany 뿐만 아니라 belongsTo, belongsToMany 전부 같은 에러가 발생하더라고요.
해결방법을 검색해봤는데,
https://www.bountysource.com/issues/27537136-limit-fails-when-used-with-belongstomany-hasmany-association-even-with-separate-true
위에 링크에서 설명하는 것 때문인가요?? 해결하려면 어떻게 해야하나요? ㅠㅠ 부탁드립니다.
몇 시간 째 막혀있어요..

**Comment by ZeroCho** [comment]
db.User가 undefined라서 그런데요.

db.User = require('./user')(sequelize, Sequelize) 이런 코드가 윗 부분에 존재 하나요?

**Comment by JeongHoon-Park** [comment]
예. 코드는 책에 있는 거랑 똑같이 썼어요...
혹시나 버전 문제일까봐 package.json 일부분도 같이 올립니다...!

 "dependencies": {
    "bcrypt": "^3.0.2",
    "connect-flash": "^0.1.1",
    "cookie-parser": "^1.4.3",
    "dotenv": "^6.1.0",
    "express": "^4.16.4",
    "express-session": "^1.15.6",
    "morgan": "^1.9.1",
    "multer": "^1.4.1",
    "mysql2": "^1.6.2",
    "passport-kakao": "0.0.5",
    "passport-local": "^1.0.0",
    "pug": "^2.0.3",
    "sequelize": "^4.41.0"
  },
  "devDependencies": {
    "nodemon": "^1.18.5"
  }

**Comment by ZeroCho** [comment]
코드 전문을 올려주셔야 할 것 같습니다! index.js요

**Comment by JeongHoon-Park** [comment]
여기 있습니닷...!

const Sequelize = require('sequelize');
const env = process.env.NODE_ENV || 'development';
const config = require('../config/config.json')[env];
const db = {};

const sequelize = new Sequelize(
	config.database, config.username, config.password, config,
);

db.sequelize = sequelize;
db.Sequelize = Sequelize;
db.User = require('./user.js')(sequelize, Sequelize);
db.Post = require('./post.js')(sequelize, Sequelize);
db.Hashtag = require('./hashtag')(sequelize, Sequelize);
db.User.hasMany(db.Post);
db.Post.belongsTo(db.User);
db.Post.belongsToMany(db.Hashtag, {through : 'PostHashtag'});
db.Hashtag.belongsToMany(db.Post, {through : 'PostHashtag'});

db.User.belongsToMany(db.User, {
	foreignKey: 'followingId',
	as : 'Followers',
	through: 'Follow',
});

db.User.belongsToMany(db.User, {
	foreignKey: 'followerId',
	as: 'Followings',
	thorugh : 'Follow',
});

module.exports = db;

**Comment by ZeroCho** [comment]
번거로우시겠지만 마지막으로 user.js도 올려주세요 return 부분에서 문제가 있을 수 있겠네요.

**Comment by JeongHoon-Park** [comment]
아닙니다..! 번거롭기는요..!

module.exports = (sequelize, DataTypes) => {
	sequelize.define('user', {
		email:{
			type: DataTypes.STRING(40),
			allowNull: false,
			unique: true,
		},
		nick: {
			type: DataTypes.STRING(15),
			allowNull: false,
		},
		password: {
			type: DataTypes.STRING(100),
			allowNull: true,
		},
		provide: {
			type: DataTypes.STRING(10),
			allowNull: false,
			defaultValue: 'local',
		},
		snsId: {
			type: DataTypes.STRING(30),
			allowNull: true,
		},
	}, {
		timestamps: true,
		paranoid: true,
	})
};

**Comment by ZeroCho** [comment]
return sequelize.define 하셔야됩니다!

**Comment by JeongHoon-Park** [comment]
감사합니다!

**Comment by woong9149** [comment]
module.exports = (sequelize, DataTypes) => {
    sequelize.define('user', {
        email:{
            type: DataTypes.STRING(40),
            allowNull:true,
            unique: true,
        },
        nick: {
            type: DataTypes.STRING(15),
            allowNull: false,
        },
        password: {
            type: DataTypes.STRING(100),
            allowNull: true,
        },
        provider: {
            type: DataTypes.STRING(10),
            allowNull: false,
            defaultValue : 'local',
        },
        snsId: {
            type: DataTypes.STRING(30),
            allowNull: true,
        },
    }, {
        timestamps: true,
        paranoid: true,
    })

    return sequelize.define;
};

이렇게   return sequelize.define; 를 해야된다는 말씀 맞나요 ?
계속 똑같은 오류가 뜨네요 흡 ㅠㅠ

**Comment by ZeroCho** [comment]
@woong9149 마지막에 return sequelize.define하시는 게 아니라 위에 sequelize.define('user')가 있는 부분 앞에 return을 붙여야합니다.
