### ISSUE TITLE
12.5 웹소켓으로 채팅 구현중 body-parser error

### ISSUE THREAD

**Issue by gimdongwon** [ZeroCho/nodejs-book#228]
room.html 에서 router로 post 요청을 보낼 때 title값이 계속 null로 와서 해당 router에서 찍어보니 req.body의 값을 가져오지 못합니다.

찾아보던 중 body-parser로 추가하니 req.body 값을 가져왔습니다.

혹시 body-parser를 이용하지 않아도 form에 있는 데이터를 가져올 수 있나요?? 

혹시라도 참고 하실분 있을까해서 이슈 남깁니다

**Comment by ZeroCho** [comment]
책 보시면 이미 바디파서 미들웨어 추가되어 있습니다. 없이는 req.body 추가 안됩니다.

**Comment by gimdongwon** [comment]
아 제가 3쇄 본인데 업데이트가 안된 책인가 보네요!

https://github.com/ZeroCho/nodejs-book/blob/master/ch12/12.5/gif-chat/app.js

이 링크 참고해서 공부 중인데 여기 코드에도 아직 추가가 안된거 같아서 추가가 필요해보입니다!!

ps : 책 너무 잘 보고 있습니다. 쉽게 풀어서 써주셔서 감사합니다 :)

**Comment by ZeroCho** [comment]
저기 express.json 이 바디파서입니다. body-parser 자체는 더이상 쓰지 않는 라이브러리입니다.

**Comment by gimdongwon** [comment]
아아 제가 urlencoded를 빠뜨렸네요 ㅜㅜ 확인감사합니다. 덕분에 좋은 공부했습니다!! 늦은시간 빠른답변 감사합니다.
