### ISSUE TITLE
이 부분에 return이 꼭 필요한 것인가요?

### ISSUE THREAD

**Issue by cleamer** [ZeroCho/nodejs-book#243]
https://github.com/ZeroCho/nodejs-book/blob/a481281815563943dd0d28c693b92c5fa9cdf7ac/ch4/4.2/restServer.js#L56

return req.on("end", ... ) 
req에서 body를 모두 읽어 req.on("end", ... )의 평가가 끝나면 return되기 때문에 안에 있는 56번째 줄의 return은 없어도 되는거 아닌가요?

**Comment by ZeroCho** [comment]
네 없어도됩니다만 res.json res.send res.end 앞에 return을 붙이는 게 좋은 습관입니다.
