### ISSUE TITLE
P.555 socket.request.headers.referer 에 roomId가 포함되지 않는데 방법이 없을까요?

### ISSUE THREAD

**Issue by gony0811** [ZeroCho/nodejs-book#274]
const req = socket.request;
    const { headers: { referer } } = req;
    const roomId = referer
      .split('/')[referer.split('/').length - 1]
      .replace(/\?.+/, '');

이 부분에서 referer의 값이 127.0.0.1:8005 까지만 표시되고 있어서 roomId를 추출할 수 없는데.. 무엇이 문제인지.. 방법이 없을까요?
![error](https://user-images.githubusercontent.com/51458279/160972514-4df4490c-f308-4f4f-84c6-4316696bfed1.jpg)

**Comment by ZeroCho** [comment]
socket.io 버전 문제로 결과가 달라진 것 같은데요. 몇 버전 사용하시나요?

**Comment by gony0811** [comment]
"socket.io": "^2.4.1" 버전을 사용하고 있습니다.

**Comment by ZeroCho** [comment]
혹시 브라우저는 어떤 것 사용하시나요?

**Comment by gony0811** [comment]
> 혹시 브라우저는 어떤 것 사용하시나요?

크롬 브라우저를 사용하고 있습니다. 버전은 아래와 같습니다.
버전 99.0.4844.82(공식 빌드) (64비트)

**Comment by ZeroCho** [comment]
이게 무언가 업그레이드 돼서 헤더 전송을 막은 것 같습니다.
socket.on('join') 이벤트를 따로 만들고 브라우저에서는 emit과 함께 방아이디를 보내서 연결 진행해야 할 것 같습니다.

**Comment by gony0811** [comment]
아 감사합니다. 
알려주신 chat.html에서 join 이벤트를 emit해서 방아이디를 넘기는 방법으로 해결했습니다. 
감사합니다!!!
