### ISSUE TITLE
책에 오타를 발견해서 이곳에 말씀드려요

### ISSUE THREAD

**Issue by chahaun** [ZeroCho/nodejs-book#30]
Nodejs 교과서 보면서 열심히 공부해보고 있습니다~
다름아니라 282페이지에 로우를 삭제하는 쿼리부분에
User.destory로 오타가 있어서 알려드려요
알고 계셨던 부분이라면 죄송합니다 .. ㅎㅎ 책이 완벽했으면 하는 바램이라서요!!

**Comment by ZeroCho** [comment]
앗 감사합니다. 3쇄에 반영하겠습니다! ㅠㅠ
