### ISSUE TITLE
p.547 몽구스 연결에러

### ISSUE THREAD

**Issue by hyperhand9** [ZeroCho/nodejs-book#304]
몽구스 버전 6.3.4 기준으로 mongoose connect 옵션에서 useCreateIndex 사용시 에러가 발생하는군요.
아래 에러를 발생시면서요.
MongoParseError: option usecreateindex is not supported

제거하니까 연결이 정상적으로 되구요.

**Comment by ZeroCho** [comment]
#236 
네 5쇄에서 수정되었습니다.
