### ISSUE TITLE
ch4.2  제출 시 오류

### ISSUE THREAD

**Issue by nhjbest22** [ZeroCho/nodejs-book#307]
codespace에서 ch.4.2 의 코드를 node를 통해 실행시킨 후 등록 버튼을 누르면 다음과 같은 오류가 발생합니다.
  
![image](https://user-images.githubusercontent.com/67857712/172575045-99dab517-bc6a-40f9-bbeb-25d566f3786c.png)

![image](https://user-images.githubusercontent.com/67857712/172574912-a5f9fca1-9211-47f7-adeb-a165112c5ae7.png)

단순히 codespace 의 문제일까요?

**Comment by ZeroCho** [comment]
전부다 경로를 못 찾네요(restFront.css랑 restFront.js 포함).

**Comment by nhjbest22** [comment]
서버의 경우 node restServer 명령어를 통해 열었습니다. Local에서 돌리면 문제가 없는데 Codespace를 통해 돌리면 저런 문제가 생기더라구요

**Comment by nhjbest22** [comment]
혹시 제출을 누르면 url 뒤에 /?가 붙는것도 js와 css를 경로 상의 문제로 불러오지 못해서 그런걸까요?
