### ISSUE TITLE
7.6.2 models/comment.js 

### ISSUE THREAD

**Issue by YoungDogg** [ZeroCho/nodejs-book#308]
책 정말 잘 보고 있습니다. 

`created_at: {
          type: Sequelize.DATE,
          allowNull: true, //            책의 DB테이블에 따르면 allowNull: false로 정정 해야 합니다, 
          defaultValue: Sequelize.NOW,
        }`

좋은 책 만드는데 도움주고 싶습니다

**Comment by ZeroCho** [comment]
created_at은 allownull이 true가 맞습니다.

**Comment by YoungDogg** [comment]
답변감사합니다
제가 allow null : false라고 한 이유는 
7.4.2 테이블 생성하기에서 comments 테이블 코드를 보고 말한 것입니다.

또한 7.4.2 테이블의 users 테이블을 보고 만든 models/user.js 에선 create_at의 allownull은 true로 되어있었습니다.
users와 comments 둘 다 7.4.2에서 Not Null 상태였습니다.

혹시 commments엔 allow null: true로 해야 하는 이유를 제가 놓친 건가요?

답변 감사합니다

**Comment by YoungDogg** [comment]
> created_at은 allownull이 true가 맞습니다.

답변감사합니다
제가 allow null : false라고 한 이유는
7.4.2 테이블 생성하기에서 comments 테이블 코드를 보고 말한 것입니다.

또한 7.4.2 테이블의 users 테이블을 보고 만든 models/user.js 에선 create_at의 allownull은 true로 되어있었습니다.
users와 comments 둘 다 7.4.2에서 Not Null 상태였습니다.

혹시 commments엔 allow null: true로 해야 하는 이유를 제가 놓친 건가요?

답변 감사합니다

**Comment by ZeroCho** [comment]
comment는 allowNull: false이고, created_at은 allowNull: true입니다.
