### ISSUE TITLE
자바스크립트 타이핑 실수 확인 기능

### ISSUE THREAD

**Issue by gwnuysw** [ZeroCho/nodejs-book#31]
안녕하세요 책 잘보고 있습니다.

그냥 atom으로 자바스크립트 작성하다가 실행 해보면 분명히 코드가 맞는데 오류가 날때가 많습니다. 한참 찾다가 그냥 타입핑실수 라는것을 알게 되면 무진장 허무한데요 atom에다가 Jslint 패키지를 달면 파일 저장할 때마다 사소한 오류를 찾아주더라구요. atom사용하시는 분들 Jslint 추천합니다!

/+ eslint도 소개해주시면 좋을 것같습니다.

**Comment by ZeroCho** [comment]
아아 이 저장소에는 eslintrc라고 eslint를 켤 수 있는 파일이 있습니다. eslint를 사용하시면 자동으로 코드 체킹이 될 겁니다~.

**Comment by gwnuysw** [comment]
> 아아 이 저장소에는 eslintrc라고 eslint를 켤 수 있는 파일이 있습니다. eslint를 사용하시면 자동으로 코드 체킹이 될 겁니다~.

감사합니다
