### ISSUE TITLE
질문이 있습니다. 12.5장 몽고디비 연결 관련 오류. 기존에 있던 방식들은 모두시도하여 글 남깁니다.

### ISSUE THREAD

**Issue by kwan-yoon** [ZeroCho/nodejs-book#322]
const mongoose = require('mongoose');

const { MONGO_ID, MONGO_PASSWORD, NODE_ENV } = process.env;
const MONGO_URL = `mongodb://${MONGO_ID}:${MONGO_PASSWORD}@localhost:27017/admin`;

const connect = () => {
if(NODE_ENV !== 'production') {
mongoose.set('debug', true);
}
mongoose.connect(MONGO_URL, {
dbName: 'gifchat',
userNewUrlParser: true
}, (error) => {
if(error) {
console.log('몽고디비 연결 에러', error);
} else {
console.log('몽고디비 연결 성공');
}
});
};

mongoose.connection.on('error', (error) => {
console.error('몽고디비 연결 에러', error);
});

mongoose.connection.on('disconnected', () => {
console.error('몽고디비 연결이 끊겼습니다. 연결을 재시도합니다.');
connect();
});

module.exports = connect;

12.5장을 진행했을때 계속 에러가 납니다.
몽고디비 연결이 끊겼다며 연결을 재시도 하라고 나옵니다.
issue에 등록한것처럼 createIndex도 제거하였고,
27017 포트에 몽고디비를 올리고 확인했을때, 계정 또한 생성되어있습니다.

그래도 npm start를 하게 되면 계속 무한로딩이 걸립니다.
왜그러는걸까요?

**Comment by ZeroCho** [comment]
useNewUrlParser 오타입니다.

**Comment by kwan-yoon** [comment]
아.. 며칠동안 계속 안돼서 이것저것 다해봤는데도 안됐는데ㅠㅠ 허무하군요.. 
몽고디비 drop부터 권한까지 계속 log가 몽고디비 관련된것밖에 보이지 않아서 정확한 디버깅이 안됐거든요..
도움주셔서 감사합니다.
