### ISSUE TITLE
92, 93 페이지 helloWorld.js 실습 관련 이슈입니다.

### ISSUE THREAD

**Issue by gusdn3477** [ZeroCho/nodejs-book#339]
안녕하세요~

교재 잘 보고 있습니다.

다름이 아니라  92 페이지의 <3.2 JS 파일 직접 실행하기> 실습 코드 관련 의견 남깁니다.

helloWorld.js 파일을 아무 폴더 안에 만들어도 상관이 없다고 하셨는데요.

바탕화면에서 파일을 만들고 윈도우에서 cmd 켠 뒤, 해당 명령어를 입력하니 

Error: Cannot find module 'C:\Users\gusdn\helloWorld'

라고 떠서, helloWorld.js 파일을 해당 경로로 이동하니 잘 실행되었습니다.

이유는 당연하게도 경로 차이일 것 같은데, 

사실 책을 처음 딱 읽었을 때에는 node.js가 어떤 경로든 간에 루트부터 하위 디렉토리를 뒤져가며 해당 파일을 찾나? 라는 생각이 들었습니다.

제가 node.js를 예전에 설치하고 현재는 nvm으로 관리중이라 저만 이런 에러가 뜰 수도 있어서 이 이슈가 모두에게 뜨는 지 확실하지는 않습니다만..

그래도 일단 이슈 남깁니다.

**Comment by ZeroCho** [comment]
helloWorld.js 파일을 아무 폴더 안에 만들어도 상관 없다고 한 것이지, 실행을 아무 폴더 안에서 해도 된다고 한 것이 아닙니다. 실행은 당연히 helloWorld.js가 있는 폴더에서 해야죠.
