### ISSUE TITLE
 ch9/9.4/nodebird/app.js 에서 posts 라우터 코드 추가요청

### ISSUE THREAD

**Issue by YongHoonJJo** [ZeroCho/nodejs-book#34]
안녕하세요! 
9.4 파트에서 routes/post.js 라우터에 대한 내용은 있는데, app.js 에서 해당 라우터에 대한 등록이 안되어 있는 것 같습니다.
`const postRouter = require('./routes/post');`
`app.use('/post', postRouter);`
위 두줄을 추가해야할 것 같은데, 확인 부탁드립니다!!

**Comment by ZeroCho** [comment]
책과 코드에 관심을 가져주셔서 감사합니다!
이 부분은 책에 나오는 부분으로 책에서 9.5절에 해당 부분을 연결합니다.
당연히 용훈님이 말씀해주시는 부분이 맞지만, 코드의 기준을 해당 파트가 끝날 때 시점으로 하고 있어서요. 9.4절이 끝날 때는 아직 연결하지 않은 상태라서 그렇게 두었습니다.

다시 한 번 감사드립니다.
