### ISSUE TITLE
cache 관련 코드

### ISSUE THREAD

**Issue by frankradio** [ZeroCho/nodejs-book#341]
3pan 브랜치의 ch3/3.4 폴더에 있는 캐시 관련 코드는 "개정3판" 책 내용에는 포함되어 있지 않습니다.
혹시 책에서 삭제되거나 다른 챕터로 이동되었는지요?
- cache.js
- cacheRequire2.js
- cacheTest.js
- cachRequire1.js

**Comment by ZeroCho** [comment]
개정3판은 아직 출간 안 되었는데요?.

**Comment by frankradio** [comment]
길벗에서 원고를 받아서 베타테스트를 하고 있습니다.
담당자 분께서 오류 제보를 여기에 등록하라고 하셔서 올렸습니다.
