### ISSUE TITLE
p.329 mysqlworkbench 설치 명령어

### ISSUE THREAD

**Issue by freelife1191** [ZeroCho/nodejs-book#343]
`--cask`를 붙이지 않고 `brew install mysqlworkbench` 만 입력해도 설치가 되므로 `--cask`는 빼도 될 것 같습니다

**Comment by ZeroCho** [comment]
설치 되는 것은 확인했으나
https://formulae.brew.sh/cask/mysqlworkbench#default
에 --cask 붙이도록 되어 있어 혹시나 모를 상황에 대비하기 위해 붙이는 걸로 놔두겠습니다.
