### ISSUE TITLE
/ch6/6.5.2/learn-express/app.js 코드 누락

### ISSUE THREAD

**Issue by frankradio** [ZeroCho/nodejs-book#344]
아래의 14라인과 15라인 사이에 코드가 누락되어 있습니다. (책에는 있음)

`app.set('view engine', 'html');`

![image](https://user-images.githubusercontent.com/4101552/197684241-3c9a7ddb-0b8c-40f1-b03c-4588c92e14b3.png)

**Comment by ZeroCho** [comment]
감사합니다~
