### ISSUE TITLE
566페이지 문장 중복

### ISSUE THREAD

**Issue by frankradio** [ZeroCho/nodejs-book#346]
566페이지의 아래 문장이 중복되어 어색합니다.

따라서 그림 10-19 **다양한 환경의 비밀 키를 발급하는 카카오와 같이 다양한 환경의 비밀 키를 발급하는 카카오처럼** 환경별로 키를 구분해서 발급하는 것이 바람직합니다.

**Comment by ZeroCho** [comment]
실제 책에 문제 없음
