### ISSUE TITLE
/ch11/11.1/nodebird/node-test.mjs - 에러 발생

### ISSUE THREAD

**Issue by frankradio** [ZeroCho/nodejs-book#347]
5번째 라인의 아래 코드에서 Cannot read properties of undefined (reading 'strictEqual') 에러가 발생합니다.

`assert(1 + 1).strictEqual(3);`

아래와 변경되어야 합니다.

`assert.strictEqual(1 + 1, 3);`

**Comment by ZeroCho** [comment]
감사합니다~
