### ISSUE TITLE
sequelize chapter 9

### ISSUE THREAD

**Issue by Holy-h** [ZeroCho/nodejs-book#42]
http://docs.sequelizejs.com/manual/upgrade-to-v5.html

sequelize가 버전 5로 변경되면서 함수 이름자체가 바뀌었더라고요.
issue에 써두신 것 같긴 한데, 예시 코드는 그대로 find를 사용하고 있어서 해결하는 데 오래 걸렸네요.

책 설명에 따라서 공부하시는 다른 분들도 User.find가 function이 아니라고 나오는 분들이 계신다면, 위 사이트를 참고하셔서 find -> findOne을 사용하시길 바랍니다.

**Comment by ZeroCho** [comment]
네 맞습니다. 지난주에 버전 5가 되면서 문제가 생겼습니다. 4쇄에서 전체적으로 수정할 예정입니다.
where에서 undefined가 안 들어가는 문제도 추가적으로 존재합니다.
`where: { id: req.user && req.user.id }` 이 부분입니다.

**Comment by Holy-h** [comment]
지금 그 부분이 막혀서 들어왔었는데, 
`Error: WHERE parameter "id" has invalid "undefined" value`
이 에러 발생하는 게 버전 5로 변경되었기 때문인가요?
해결 방법 여쭤봐도 될까요?

**Comment by ZeroCho** [comment]
4버전을 사용하거나
5버전에서는
```
if (req.user) {
  User.findOne({ })
}
```
이런식으로 가드해주어야 합니다.

**Comment by bny64** [comment]
sequelize 5버전으로 올라오면서 위와 같은 문제가 발생하는데 아마 undefined를 에러처리를 하는 것 같은데
req.user가 undefined가 들어오면 null로 변수를 바꿔서 예외처리를 하고 있는데 올바른 방법인가요?
위에 올려주신 방법도 또 하나의 방법인 것 같습니다.

**Comment by shi-jh** [comment]
저도 같은 문제인데... 가드를 해줘야한다고 하는데, 구체적으로 어떻게 해야하는것인가요? 초보라 다아시는것을 물어보는 것 같아서..

**Comment by ZeroCho** [comment]
@bny64 null로 해도 정상 동작하긴 하겠지만, 의미상 좀 이상한 것 같습니다.
