### ISSUE TITLE
Client does not support authentication protocol requested by server; consider upgrading MySQL client

### ISSUE THREAD

**Issue by ZeroCho** [ZeroCho/nodejs-book#45]
mysql prompt에 (터미널 아님. mysql -u root -p 접속화면임)
```
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '비밀번호';
```
입력하시면 됩니다.

**Comment by Xsolute** [comment]
MySQL을 설치할 때에 Authentication Method를 설정할 때에 새로운 인증 형식(Use Strong Password Encryption for Authentication)으로 설치하는 경우에도 저 오류가 발생했는데, Use Legacy Authentication Method로 변경하여 설치하는 경우에도 해결 가능한 것 같습니다.

**Comment by ZeroCho** [comment]
@Xsolute 네 맞습니다. 5.7과 8.0 비밀번호 인증 형식이 달라서 발생하는 문제입니다.

**Comment by ZeroCho** [comment]
https://github.com/mysqljs/mysql/pull/1962

**Comment by ZeroCho** [comment]
mysql2 2버전에서 수정되었다는데 체크해보기

**Comment by ZeroCho** [comment]
mysql2의 2버전을 사용하면 해결됩니다.

**Comment by ZeroCho** [comment]
mariadb의 경우 set password = password("새로운 비밀번호 입력");
