### ISSUE TITLE
챕터 10.3 406 페이지 관련 문의

### ISSUE THREAD

**Issue by MAR1026** [ZeroCho/nodejs-book#50]
최근 Node.js 교과서를 통해 노드를 공부하고 있는 학생입니다.
다름이 아니오라 챕터 10 웹 API 서버 만들기 파트 중
406페이지 마지막 부분에서 제 경우 약간의 문제가 발생하는 것 같아 문의를 드립니다.
```
router.get('/test', verifyToken, (req, res) => {
 res.json(req.decoded);
});
```
이렇게 하니 뒤에 있는 호출 서버를 구현해도 아무런 결과값이 나오지 않아,
`res.json(req.decoded);` -> `return res.json(req.decoded);`
이런 식으로 바꾸니 정상적으로 값이 나옵니다.

제 환경에서의 문제인지, 혹은 누락된 부분인 것인지 검토 부탁드리겠습니다.
감사합니다.

**Comment by ZeroCho** [comment]
일단 이 부분에서만 말씀드리자면 return 여부는 상관이 없습니다. 다른 부분 문제인 듯 하네요.
