### ISSUE TITLE
sequelize hasMany부분 에러 

### ISSUE THREAD

**Issue by Eyes0n** [ZeroCho/nodejs-book#52]
저도 TypeError: Cannot read property 'hasMany' of undefined 오류 메시지가 떠서 해결 하던 중 이슈글에 해당 글이 있어서 시도 해봤데요  (seq, data) => { sequelize.define() retrun sequelize.define; } 형식으로 해줘도 안되서 또 검색하다가 다른 방법으로 즉시 함수로 만들어 보기도 했는데 마찬가지로 안되더군요. 하지만 let 변수를 사용해서 리턴 해주면 (seq, data) => { let user = sequelize.define() retrun user; } 실행이 됩니다.  왜 변수에 할당후 리턴해주는 조건에서만 실행되는거죠? 소스는 강의 소랑 같습니다.

**Comment by YongHoonJJo** [comment]
sequelize.define() 을 리턴해야하는 것 같든데, 중괄호가 아니라 소괄호일거에요!
