### ISSUE TITLE
Ch.9-3 kakao 로그인 해결.

### ISSUE THREAD

**Issue by Rootjang92** [ZeroCho/nodejs-book#56]
안녕하세요. 문의가 있어서 글 남깁니다.

7월 31일자로 kakao redirect 부분에 path창이 없어지고 

URI 부분만 남아있는데 이건 처리를 어떻게 해야 될까요??

여러가지 시도를 해봤는데 잘 되지 않네요.

감사합니다.

**Comment by ZeroCho** [comment]
로그인 Redirect URI 부분에 똑같이 http://localhost:8001/auth/kakao/callback를 넣어도 안 되나요?

**Comment by Rootjang92** [comment]
> 로그인 Redirect URI 부분에 똑같이 [http://localhost:8001/auth/kakao/callback를](http://localhost:8001/auth/kakao/callback%EB%A5%BC) 넣어도 안 되나요?

해결 했습니다 감사합니다!!
