### ISSUE TITLE
Ch 10-2 field list 문제

### ISSUE THREAD

**Issue by Rootjang92** [ZeroCho/nodejs-book#57]
안녕하세요 또 질문 드립니다. 

10-2 Nodebird api를 따라 만들고 있는데

서버를 시작하면 Unknown column 'domains.userId' in 'field list' 라는 오류가 발생합니다.

혹시나 해서 코드를 복붙해봤는데도 오류가 해결이 안되고 있습니다.

현재 구글링도 진행중입니다. 감사합니다.

**Comment by ZeroCho** [comment]
코드 수정으로는 해결이 안 되고 디비 테이블을 지웠다 다시 만드셔야 합니다.

**Comment by Rootjang92** [comment]
> 코드 수정으로는 해결이 안 되고 디비 테이블을 지웠다 다시 만드셔야 합니다.

seed:undo로 지우고 다시 create 해봤는데 같은 에러가 발생합니다.

**Comment by Rootjang92** [comment]
> 코드 수정으로는 해결이 안 되고 디비 테이블을 지웠다 다시 만드셔야 합니다.

drop으로 하니깐 수정되었습니다. 항상 빠른 답변 감사합니다 ^^
