### ISSUE TITLE
ch4.3 문의

### ISSUE THREAD

**Issue by JungTa** [ZeroCho/nodejs-book#59]
restServer.js를 node로 실행 시킨 후
restFont.html을 실행시키면 CORS 오류가 뜹니다.

운영체제: Mac Mojave 10.14.6
브라우저: Chrome 버전 76.0.3809.100(공식 빌드) (64비트)

오류내용 입니다.
restFront.js:57 Access to XMLHttpRequest at 'file:///users' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

**Comment by ZeroCho** [comment]
HTML 파일을 실행하시면 안 되고요. 브라우저에서 localhost:8085 주소로 접근하셔야 합니다.
