### ISSUE TITLE
ch 9.5.1 스스로 해보기 질문입니다.

### ISSUE THREAD

**Issue by JungTa** [ZeroCho/nodejs-book#60]
팔로잉 끊기 해봤는데
Follow 모델 require해서 쓰려고 했는데 이걸 어디서 어떻게 받아야 할 지 모르겠더라고요.
models 폴더 안에 정의한 모델이 아니라서
그래서 삽질하다가 
```js
const {
  User,
  sequelize: {
    models: { Follow },
  },
} = require('../models');
```

이런 식으로 가져와서 썼는데 잘 돌아가더군요.
이런방식으로 가져오는게 맞는 건가요?
아니면 더 좋은 방법이 있을까요?

**Comment by ZeroCho** [comment]
Follow에 직접 접근해야한다면 그렇게 할 수밖에 없습니다.
기존 User를 통해서 한다면
```
const user = await User.findOne({ where: { id } });
await user.removeFollowing(상대id);
```

이런식으로 합니다.

**Comment by JungTa** [comment]
user에 add만 있는 줄 알았는데 remove도 있었군요!
감사합니다^^
