### ISSUE TITLE
15장 레디스 질문

### ISSUE THREAD

**Issue by kyungrae** [ZeroCho/nodejs-book#74]
안녕하세요. 

15장 공부하면서 질문 남깁니다.
express-session과 connect-redis 모듈 버전이 올라가면서 기존 코드가 작동하지 않아서 아래 코드와 같이 바꿔서 문제를 해결 했습니다.

여기서 질문이있는데요. 보통 요청을 보내는 쪽이 클라이언트 요청에 대한 응답을 보내는 쪽이 서버라고 하는데 이런 관점에서 보면 레디스는 세션 정보를 저장하고 응답하는 역할을 하니 레디스 서버라는 표현이 더 맞는것 같은데 왜 클라이언트라고 표현할까요?

```
const session = require("express-session");
const redis = require("redis");
const RedisStore = require("connect-redis")(session);

const redisClient = redis.createClient({
  host: process.env.REDIS_HOST,
  port: process.env.REDIS_PORT,
  password: process.env.REDIS_PASSWORD,
  logErrors: true
});

const sessionOption = {
  resave: false,
  saveUninitialized: false,
  secret: process.env.COOKIE_SECRET,
  cookie: {
    httpOnly: true,
    secure: false
  },
  store: new RedisStore({ client: redisClient })
};
```

참고로 이미 알고 계실것 같지만 lightsail에 서비스를 배포할 때, npm install bcrypt를 하기 위해 root 권한이 필요해서 중간에 sudo -i가 필요해요.

감사합니다.

**Comment by ZeroCho** [comment]
네. 저도 이 부분 문제 발견해서 개정판에서 수정 예정입니다.
레디스 서버에 대한 클라이언트라서 클라이언트라고 표현합니다. 레디스 서버는 실제로 깔려 있는 프로그램이 서버이고요. 클라이언트를 통해서 서버에 접속하기 때문입니다.

**Comment by kyungrae** [comment]
빠른 답변 감사합니다!
