### ISSUE TITLE
[p.479] controllers와 routers 의 index.js 파일 복사 내용 누락

### ISSUE THREAD

**Issue by wiseguy77** [ZeroCho/nodejs-book#765]
에러 내용을 확인하고 직접 각 경로에 있는 index.js 파일들을 복사하여 쉽게 해결할 수 있는 문제입니다.
다만 초보들을 위해 친절하게 복사할 파일 목록까지 알려주시려는 목적의 완성도를 높히시는 데 도움이 되었으면 좋겠습니다^^

**Comment by ZeroCho** [comment]
485쪽에 내용 있습니다.
