### ISSUE TITLE
[p.807, p.808] TSXXXX 에러 번호 관련 오타 수정 

### ISSUE THREAD

**Issue by wiseguy77** [ZeroCho/nodejs-book#769]
p.807 맨 아래 "TS2769 에러는 ..." => "TS2322 에러는 ..."
p.808 맨 위 "TS2769 에러를 해결하면 ..." => "TS2322 에러를 해결하면 ..." 
로 수정되어야 할 것으로 보입니다.

**Comment by ZeroCho** [comment]
passport/kakaoStrategy.ts:8:5 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(options: StrategyOption, verify: VerifyFunction): Strategy', gave the following error.
    Type 'string | undefined' is not assignable to type 'string'.
      Type 'undefined' is not assignable to type 'string'.
  Overload 2 of 2, '(options: StrategyOptionWithRequest, verify: VerifyFunctionWithRequest): Strategy', gave the following error.
    Type 'string | undefined' is not assignable to type 'string'.
      Type 'undefined' is not assignable to type 'string'.

8     clientID: process.env.KAKAO_ID,

이걸 해결한 것이라서 TS2769 에러가 맞습니다.
