### ISSUE TITLE
10.7 CORS 적용 시, 특정 도메인 허용설정

### ISSUE THREAD

**Issue by illhumored** [ZeroCho/nodejs-book#85]
안녕하세요.
CORS 적용하면서 궁금한 내용이 있어 여기 문의 드립니다.

특정 도메인만 허용하도록 설정 하는 부분(p.425) 인데요.

전체허용 -> 특정 도메인만 허용 변경 시,
CORS 설정 이전과 같은 오류가 발생해서요.

혹시.. 버전에 따른 추가로 설정이 필요한 부분이 있을까요..?

답변 미리 감사드립니다..!

(크롬 콘솔 에러 내용)
Access to XMLHttpRequest at 'http://localhost:8002/v2/token' from origin 'http://localhost:8003' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by ZeroCho** [comment]
console.log(req.get('origin')) 위에 해보시겠어요? undefined가 뜨면 req.get('origin')을 따로 설정해야 합니다.
